trigger:
  branches:
    include:
      - master

resources:
  repositories:
  - repository: self
  - repository: templates
    type: github
    name: equinor/procosys-infra
    endpoint: 'procosys - github'

# Global variables for the pipeline
variables:
 - template: templates/variables/preservation-variables.yml@templates
 - template: templates/variables/procosys-global-variables.yml@templates

 - name: 'repositoryName'
   value: 'preservation/api'

stages:
# common stage. Docker build, tag and push
- stage: common
  displayName: 'Common'
  variables:
    envName: 'common'
    envRg: '${{ variables.envRgName }}'
    containerRegistry: '${{ variables.containerRegistryName }}'
    envGroupName: '$(globalPrefix)-$(fullAppName)-${{ variables.envName }}'
    dockerRegistryServiceConnection: '$(dockerRegistryServiceConnectionName)'
    dockerfilePath: '$(Build.SourcesDirectory)/src/Equinor.Procosys.Preservation.WebApi/Dockerfile'

  jobs:
  - template: /templates/pipelines/dockerbuild.yml@templates
    parameters:
      deploymentName: 'docker_build_push'
      dependsOn: ''
      env: 'pcs-${{ variables.envName }}'
      envGroup: '${{ variables.envGroupName }}'
      dockerfilePath: '${{ variables.dockerfilePath }}'
      buildContext: '$(Build.SourcesDirectory)/src'
      repository: '${{ variables.repositoryName }}'
      dockerRegistryServiceConnection: $(dockerRegistryServiceConnectionName)

# Dev deploy stage
- stage: dev
  displayName: 'Dev'
  dependsOn: 'common'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  variables:
    envName: 'dev'
    envRg: '${{ variables.envRgName }}'
    envGroupName: '$(globalPrefix)-$(fullAppName)-${{ variables.envName }}'
    serviceConnection: '${{ variables.nonProdServiceConnection }}'
    appServicePlan: '${{ variables.nonProdappServicePlanName }}'
    containerRegistry: '${{ variables.containerRegistryName }}' 
    aspNetCoreEnvironment: 'Development'

  jobs:
  - template: /templates/pipelines/kubernetes/preservation-deploy.yml@templates
    parameters:
      deploymentName: 'deploy_to_k8s'
      dependsOn: ''
      serviceConnection: '${{ variables.serviceConnection }}'
      env: '${{ variables.envName }}'
      envRg: 'pcs-hosting-rg'
      envGroup: '${{ variables.envGroupName }}'
      dockerImage: 'procosys.azurecr.io/preservation/api:$(Build.BuildId)'
      clusterName: 'aks-pcs-test'
      kvClientIdName: '${{ variables.kvClientIdName }}'
      kvUriName: '${{ variables.kvUriName }}'
      kvClientSecretName: '${{ variables.kvClientSecretName }}'
      kvName: '${{ variables.kvName }}'
      kvRgName: '${{ variables.envRgName }}'